# Generated by Django 5.1.3 on 2024-11-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilizador",
            name="tipo_user",
            field=models.CharField(
                choices=[
                    ("Cliente", "Cliente"),
                    ("Driver", "Driver"),
                    ("Parceiro", "Parceiro"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
